[package]
name = "cortexfs"
description = "CortexFS Agent OS ABI design core."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cortexfs-tool-sdk = { version = "0.1.0", path = "../cortexfs-tool-sdk" }
fuser = "0.17.0"
jsonschema = { version = "0.46.5", default-features = false }
keyring = "4.1.2"
listenfd = "1.0.2"
nix = { version = "0.31.3", features = ["fs", "signal", "socket", "term", "user"] }
portable-pty = "0.9.0"
rustyline = "18.0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_path_to_error = "0.1.20"
serde_yaml = "0.9"
sha2 = "0.11.0"
signal-hook = "0.3.18"
tempfile = "3.27.0"
xattr = "1.6.1"

[lints]
workspace = true
