use std::collections::{BTreeMap, HashMap};
use std::time::Instant;

use cortex_store::RequestId;
use fuse3::Inode;

use crate::execution::{FsExecutionPlane, default_execution_plane};
use crate::runtime_parents::RuntimeParents;
use crate::runtime_types::{
    AgentTask, ApiRouteInodes, ChanRuntimeInodes, ClusterTask, ConversationExportRow,
    JobRuntimeInodes, MemoryItem, PendingResponse, PreferencePair, PromptRender,
    ProviderConfigInodes, RuntimeContext, TrainingExportRow, UserModelAccessInodes,
};
use crate::{DYNAMIC_INODE_BASE, Node};

#[derive(Debug, Clone, Copy)]
struct ClusterRuntimeInodes {
    state: Option<Inode>,
    worker_state: Option<Inode>,
    worker_heartbeat: Option<Inode>,
    worker_load: Option<Inode>,
    worker_current_task: Option<Inode>,
    pending_parent: Option<Inode>,
    running_parent: Option<Inode>,
    tasks_parent: Option<Inode>,
    done_parent: Option<Inode>,
    failed_parent: Option<Inode>,
}

#[derive(Debug, Clone, Copy)]
struct AgentRuntimeInodes {
    state: Option<Inode>,
    pid: Option<Inode>,
    heartbeat: Option<Inode>,
    current_thread: Option<Inode>,
    current_task: Option<Inode>,
}

#[derive(Debug, Clone, Copy)]
struct McpRuntimeInodes {
    status: Option<Inode>,
    pid: Option<Inode>,
    workspace_content: Option<Inode>,
    workspace_refresh: Option<Inode>,
    session_state: Option<Inode>,
    session_transcript: Option<Inode>,
    session_summary: Option<Inode>,
}

#[derive(Debug, Default, Clone, Copy)]
pub struct MemoryLayerInodes {
    pub working: Option<Inode>,
    pub episodic: Option<Inode>,
    pub semantic: Option<Inode>,
    pub procedural: Option<Inode>,
    pub profile: Option<Inode>,
}

#[derive(Debug, Default)]
pub struct RuntimeState {
    pub(crate) context: RuntimeContext,
    pub(crate) nodes: BTreeMap<Inode, Node>,
    pub(crate) parent_children: BTreeMap<Inode, Vec<Inode>>,
    pub(crate) next_inode: Inode,
    pub(crate) staged: BTreeMap<(Inode, String), Inode>,
    pub(crate) outbox: BTreeMap<(Inode, String), Inode>,
    pub(crate) pending: HashMap<RequestId, PendingResponse>,
    pub(crate) cluster_tasks: HashMap<RequestId, ClusterTask>,
    pub(crate) cluster_failed_tasks: HashMap<RequestId, ClusterTask>,
    pub(crate) cluster_pending_entries: HashMap<RequestId, Inode>,
    pub(crate) cluster_running_entries: HashMap<RequestId, Inode>,
    pub(crate) cluster_task_retry_inodes: HashMap<Inode, RequestId>,
    pub(crate) agent_tasks: HashMap<RequestId, AgentTask>,
    pub(crate) memory_items: HashMap<RequestId, MemoryItem>,
    pub(crate) preference_pairs: HashMap<RequestId, PreferencePair>,
    pub(crate) prompt_renders: HashMap<RequestId, PromptRender>,
    pub(crate) audit_inode: Inode,
    pub(crate) audit_usage_inode: Inode,
    pub(crate) audit_cost_inode: Inode,
    pub(crate) user_audit_events_inode: Option<Inode>,
    pub(crate) audit_total_events: usize,
    pub(crate) audit_staged_events: usize,
    pub(crate) audit_queued_events: usize,
    pub(crate) audit_drained_events: usize,
    pub(crate) audit_error_events: usize,
    pub(crate) audit_denied_events: usize,
    pub(crate) audit_billable_events: usize,
    pub(crate) audit_tool_calls: usize,
    pub(crate) audit_agent_tasks: usize,
    pub(crate) conversation_rows: Vec<ConversationExportRow>,
    pub(crate) preference_rows: Vec<TrainingExportRow>,
    pub(crate) tool_call_rows: Vec<TrainingExportRow>,
    pub(crate) agent_trace_rows: Vec<TrainingExportRow>,
    pub(crate) conversations_export_inode: Option<Inode>,
    pub(crate) sft_export_inode: Option<Inode>,
    pub(crate) preference_export_inode: Option<Inode>,
    pub(crate) tool_calls_export_inode: Option<Inode>,
    pub(crate) agent_traces_export_inode: Option<Inode>,
    pub(crate) export_refresh_inode: Option<Inode>,
    pub(crate) export_filter_provider_inode: Option<Inode>,
    pub(crate) export_filter_model_inode: Option<Inode>,
    pub(crate) export_filter_agent_inode: Option<Inode>,
    pub(crate) export_filter_subject_inode: Option<Inode>,
    pub(crate) export_filter_space_inode: Option<Inode>,
    pub(crate) export_filter_from_inode: Option<Inode>,
    pub(crate) export_filter_to_inode: Option<Inode>,
    pub(crate) export_filter_exclude_failed_inode: Option<Inode>,
    pub(crate) export_seq: u64,
    pub(crate) drain_inode: Inode,
    pub(crate) flush_inode: Inode,
    pub(crate) gc_inode: Inode,
    pub(crate) last_control_inode: Inode,
    pub(crate) queue_depth_inode: Inode,
    pub(crate) last_drained_inode: Inode,
    pub(crate) batch_count_inode: Option<Inode>,
    pub(crate) batch_state_inode: Option<Inode>,
    pub(crate) thread_messages_inode: Option<Inode>,
    pub(crate) thread_latest_inode: Option<Inode>,
    pub(crate) thread_state_inode: Option<Inode>,
    pub(crate) thread_fingerprint_inode: Option<Inode>,
    pub(crate) thread_continue_inode: Option<Inode>,
    pub(crate) thread_pause_inode: Option<Inode>,
    pub(crate) thread_cancel_inode: Option<Inode>,
    pub(crate) external_thread_messages_inode: Option<Inode>,
    pub(crate) external_thread_latest_inode: Option<Inode>,
    pub(crate) external_thread_state_inode: Option<Inode>,
    pub(crate) external_thread_fingerprint_inode: Option<Inode>,
    pub(crate) external_subject_quota_requests_inode: Option<Inode>,
    pub(crate) tool_loop_state_inode: Option<Inode>,
    pub(crate) tool_loop_steps_inode: Option<Inode>,
    pub(crate) tool_loop_continue_inode: Option<Inode>,
    pub(crate) tool_loop_pause_inode: Option<Inode>,
    pub(crate) tool_loop_cancel_inode: Option<Inode>,
    pub(crate) tool_loop_max_steps_inode: Option<Inode>,
    pub(crate) tool_loop_max_time_ms_inode: Option<Inode>,
    pub(crate) tool_loop_max_cost_usd_inode: Option<Inode>,
    pub(crate) tool_loop_started_at: Option<Instant>,
    pub(crate) tool_loop_cost_micros: u64,
    pub(crate) memory_query_inode: Option<Inode>,
    pub(crate) memory_results_inode: Option<Inode>,
    pub(crate) memory_semantic_items_inode: Option<Inode>,
    pub(crate) memory_layer_items: MemoryLayerInodes,
    pub(crate) memory_index_state_inode: Option<Inode>,
    pub(crate) memory_index_store_inode: Option<Inode>,
    pub(crate) memory_index_source_inode: Option<Inode>,
    pub(crate) memory_index_refresh_inode: Option<Inode>,
    pub(crate) mcp_local_fs_status_inode: Option<Inode>,
    pub(crate) mcp_local_fs_pid_inode: Option<Inode>,
    pub(crate) mcp_local_fs_start_inode: Option<Inode>,
    pub(crate) mcp_local_fs_stop_inode: Option<Inode>,
    pub(crate) mcp_local_fs_restart_inode: Option<Inode>,
    pub(crate) mcp_workspace_content_inode: Option<Inode>,
    pub(crate) mcp_workspace_refresh_inode: Option<Inode>,
    pub(crate) mcp_session_state_inode: Option<Inode>,
    pub(crate) mcp_session_transcript_inode: Option<Inode>,
    pub(crate) mcp_session_summary_inode: Option<Inode>,
    pub(crate) mcp_session_search_query_inode: Option<Inode>,
    pub(crate) mcp_session_search_results_inode: Option<Inode>,
    pub(crate) agent_helper_outbox_parent: Option<Inode>,
    pub(crate) agent_helper_start_inode: Option<Inode>,
    pub(crate) agent_helper_stop_inode: Option<Inode>,
    pub(crate) agent_helper_restart_inode: Option<Inode>,
    pub(crate) agent_helper_pause_inode: Option<Inode>,
    pub(crate) agent_helper_runtime_state_inode: Option<Inode>,
    pub(crate) agent_helper_runtime_pid_inode: Option<Inode>,
    pub(crate) agent_helper_runtime_heartbeat_inode: Option<Inode>,
    pub(crate) agent_helper_runtime_current_thread_inode: Option<Inode>,
    pub(crate) agent_helper_runtime_current_task_inode: Option<Inode>,
    pub(crate) collab_task_owner_inode: Option<Inode>,
    pub(crate) collab_task_state_inode: Option<Inode>,
    pub(crate) collab_task_events_inode: Option<Inode>,
    pub(crate) collab_locks_parent: Option<Inode>,
    pub(crate) user_allowed_providers_inode: Option<Inode>,
    pub(crate) user_default_provider_inode: Option<Inode>,
    pub(crate) user_gc_inode: Option<Inode>,
    pub(crate) user_models_refresh_inode: Option<Inode>,
    pub(crate) user_models_count_inode: Option<Inode>,
    pub(crate) user_models_list_inode: Option<Inode>,
    pub(crate) user_routes: BTreeMap<&'static str, ApiRouteInodes>,
    pub(crate) user_model_access: BTreeMap<&'static str, UserModelAccessInodes>,
    pub(crate) cluster_state_inode: Option<Inode>,
    pub(crate) cluster_worker_state_inode: Option<Inode>,
    pub(crate) cluster_worker_heartbeat_inode: Option<Inode>,
    pub(crate) cluster_worker_load_inode: Option<Inode>,
    pub(crate) cluster_worker_current_task_inode: Option<Inode>,
    pub(crate) cluster_rebalance_inode: Option<Inode>,
    pub(crate) cluster_drain_inode: Option<Inode>,
    pub(crate) cluster_pause_inode: Option<Inode>,
    pub(crate) feedback_preference_outbox_parent: Option<Inode>,
    pub(crate) mcp_prompt_render_outbox_parent: Option<Inode>,
    pub(crate) cluster_pending_parent: Option<Inode>,
    pub(crate) cluster_running_parent: Option<Inode>,
    pub(crate) cluster_tasks_parent: Option<Inode>,
    pub(crate) cluster_done_parent: Option<Inode>,
    pub(crate) cluster_failed_parent: Option<Inode>,
    pub(crate) pgvector_enabled_inode: Option<Inode>,
    pub(crate) pgvector_status_inode: Option<Inode>,
    pub(crate) pgvector_collections_inode: Option<Inode>,
    pub(crate) pgvector_refresh_inode: Option<Inode>,
    pub(crate) sqlite_status_inode: Option<Inode>,
    pub(crate) postgres_status_inode: Option<Inode>,
    pub(crate) postgres_dsn_current_inode: Option<Inode>,
    pub(crate) postgres_dsn_effective_inode: Option<Inode>,
    pub(crate) postgres_dsn_source_inode: Option<Inode>,
    pub(crate) provider_url: BTreeMap<&'static str, ProviderConfigInodes>,
    pub(crate) provider_enabled: BTreeMap<&'static str, ProviderConfigInodes>,
    pub(crate) provider_health_check: BTreeMap<&'static str, Inode>,
    pub(crate) provider_health_status: BTreeMap<&'static str, Inode>,
    pub(crate) provider_health_latency_ms: BTreeMap<&'static str, Inode>,
    pub(crate) provider_health_last_error: BTreeMap<&'static str, Inode>,
    pub(crate) provider_secret_status: BTreeMap<&'static str, Inode>,
    pub(crate) provider_secret_rotate: BTreeMap<&'static str, Inode>,
    pub(crate) provider_secret_active: BTreeMap<&'static str, Inode>,
    pub(crate) provider_secret_last_rotated: BTreeMap<&'static str, Inode>,
    pub(crate) provider_secret_next_rotation: BTreeMap<&'static str, Inode>,
    pub(crate) provider_models_refresh: BTreeMap<&'static str, Inode>,
    pub(crate) chans_parent: Option<Inode>,
    pub(crate) chan_count_inode: Option<Inode>,
    pub(crate) chan_list_inode: Option<Inode>,
    pub(crate) chans: BTreeMap<String, ChanRuntimeInodes>,
    pub(crate) jobs_parent: Option<Inode>,
    pub(crate) job_count_inode: Option<Inode>,
    pub(crate) job_list_inode: Option<Inode>,
    pub(crate) jobs: BTreeMap<String, JobRuntimeInodes>,
    pub(crate) batch_count: usize,
    pub(crate) plane: Option<FsExecutionPlane>,
}

impl RuntimeState {
    pub(crate) fn new(parents: &RuntimeParents) -> Self {
        let mut state = Self::blank(parents);
        state.attach_runtime_files(parents);
        state.refresh_provider_health_statuses();
        state.refresh_user_model_access();
        state.refresh_user_routes();
        state
    }

    fn blank(parents: &RuntimeParents) -> Self {
        let mcp = mcp_runtime_inodes(parents);
        let agent = agent_runtime_inodes(parents);
        let cluster = cluster_runtime_inodes(parents);
        Self {
            next_inode: DYNAMIC_INODE_BASE,
            audit_inode: DYNAMIC_INODE_BASE,
            audit_usage_inode: DYNAMIC_INODE_BASE,
            audit_cost_inode: DYNAMIC_INODE_BASE,
            user_audit_events_inode: None,
            drain_inode: DYNAMIC_INODE_BASE,
            flush_inode: DYNAMIC_INODE_BASE,
            gc_inode: DYNAMIC_INODE_BASE,
            last_control_inode: DYNAMIC_INODE_BASE,
            queue_depth_inode: DYNAMIC_INODE_BASE,
            last_drained_inode: DYNAMIC_INODE_BASE,
            external_subject_quota_requests_inode: None,
            mcp_local_fs_status_inode: mcp.status,
            mcp_local_fs_pid_inode: mcp.pid,
            mcp_workspace_content_inode: mcp.workspace_content,
            mcp_workspace_refresh_inode: mcp.workspace_refresh,
            mcp_session_state_inode: mcp.session_state,
            mcp_session_transcript_inode: mcp.session_transcript,
            mcp_session_summary_inode: mcp.session_summary,
            mcp_session_search_query_inode: None,
            mcp_session_search_results_inode: None,
            agent_helper_outbox_parent: parents.agent_helper_outbox,
            agent_helper_runtime_state_inode: agent.state,
            agent_helper_runtime_pid_inode: agent.pid,
            agent_helper_runtime_heartbeat_inode: agent.heartbeat,
            agent_helper_runtime_current_thread_inode: agent.current_thread,
            agent_helper_runtime_current_task_inode: agent.current_task,
            collab_task_owner_inode: None,
            collab_task_state_inode: None,
            collab_task_events_inode: None,
            collab_locks_parent: parents.collab_locks,
            cluster_state_inode: cluster.state,
            cluster_worker_state_inode: cluster.worker_state,
            cluster_worker_heartbeat_inode: cluster.worker_heartbeat,
            cluster_worker_load_inode: cluster.worker_load,
            cluster_worker_current_task_inode: cluster.worker_current_task,
            cluster_pending_parent: cluster.pending_parent,
            cluster_running_parent: cluster.running_parent,
            feedback_preference_outbox_parent: parents.feedback_preference_outbox,
            mcp_prompt_render_outbox_parent: parents.mcp_prompt_render_outbox,
            cluster_tasks_parent: cluster.tasks_parent,
            cluster_done_parent: cluster.done_parent,
            cluster_failed_parent: cluster.failed_parent,
            pgvector_enabled_inode: None,
            pgvector_status_inode: None,
            pgvector_collections_inode: None,
            pgvector_refresh_inode: None,
            sqlite_status_inode: None,
            postgres_status_inode: None,
            chans_parent: parents.chans,
            jobs_parent: parents.user_jobs,
            plane: default_execution_plane(),
            ..Self::default()
        }
    }
}

const fn mcp_runtime_inodes(_parents: &RuntimeParents) -> McpRuntimeInodes {
    McpRuntimeInodes {
        status: None,
        pid: None,
        workspace_content: None,
        workspace_refresh: None,
        session_state: None,
        session_transcript: None,
        session_summary: None,
    }
}

const fn agent_runtime_inodes(_parents: &RuntimeParents) -> AgentRuntimeInodes {
    AgentRuntimeInodes {
        state: None,
        pid: None,
        heartbeat: None,
        current_thread: None,
        current_task: None,
    }
}

const fn cluster_runtime_inodes(parents: &RuntimeParents) -> ClusterRuntimeInodes {
    ClusterRuntimeInodes {
        state: None,
        worker_state: None,
        worker_heartbeat: None,
        worker_load: None,
        worker_current_task: None,
        pending_parent: parents.cluster_pending,
        running_parent: parents.cluster_running,
        tasks_parent: parents.cluster_tasks,
        done_parent: parents.cluster_done,
        failed_parent: parents.cluster_failed,
    }
}
