import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {type: 'link', label: 'Find a guide', href: '/handbook'},
    {
      type: 'category', label: 'Get Started', collapsed: false,
      items: ['getting-started', 'packaging', 'using-cortexfs'],
    },
    {
      type: 'category', label: 'Build & Evaluate', collapsed: false,
      items: [
        'developing-cortexfs', 'extensions', 'channels', 'evaluation',
        {type: 'doc', id: 'aimock-testing', label: 'Provider Mock Tests'},
        'futureagi',
      ],
    },
    {
      type: 'category', label: 'Architecture', collapsed: true,
      items: [
        {type: 'doc', id: 'architecture', label: 'System Architecture'},
        {type: 'doc', id: 'internal-architecture', label: 'Internal Architecture'},
        {type: 'doc', id: 'naming-guide', label: 'Naming Guide'},
        {type: 'doc', id: 'DESIGN', label: 'Visual Design'},
        {type: 'doc', id: 'proofs/verus', label: 'Verus Proofs'},
      ],
    },
    {
      type: 'category', label: 'Client Reference', collapsed: true,
      items: [
        {type: 'doc', id: 'CTX', label: 'ctx Coreutils Design'},
        'agent-sh', 'chatui', 'paths',
      ],
    },
    {
      type: 'category', label: 'Specification', collapsed: true,
      items: [{type: 'autogenerated', dirName: 'spec'}],
    },
  ],
};

export default sidebars;
