import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'getting-started',
    'using-cortexfs',
    'developing-cortexfs',
    {
      type: 'category',
      label: '拓展阅读',
      collapsed: true,
      items: [
        {type: 'doc', id: 'DESIGN', label: '设计说明'},
        {type: 'doc', id: 'CTX', label: 'ctx Coreutils 设计'},
        {type: 'doc', id: 'agent-sh', label: 'agent.sh'},
        {type: 'doc', id: 'aimock-testing', label: 'AIMock 测试'},
        {
          type: 'category',
          label: 'v1 规范',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'spec'}],
        },
      ],
    },
  ],
};

export default sidebars;
