import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'DESIGN',
    'CTX',
    'agent-sh',
    {
      type: 'category',
      label: 'v1 Spec',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'spec'}],
    },
  ],
};

export default sidebars;
