[package]
name = "cortex-cli"
description = "CortexFS command-line interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "cortex"
path = "src/main.rs"

[dependencies]
cortex-core = { version = "0.1.0", path = "../cortex-core" }
cortex-providers = { version = "0.1.0", path = "../cortex-providers" }
cortex-store = { version = "0.1.0", path = "../cortex-store" }
cortexd = { version = "0.1.0", path = "../cortexd" }
cortexfs = { path = "../cortexfs" }

[lints]
workspace = true
